//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//       LottieGen version:
//           7.1.0+ge1fa92580f
//       
//       Command:
//           LottieGen -GenerateColorBindings -Language CSharp -Public -WinUIVersion 2.4 -InputFile fire.json
//       
//       Input file:
//           fire.json (52536 bytes created 10:37+03:00 Mar 15 2022)
//       
//       LottieGen source:
//           http://aka.ms/Lottie
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
// ___________________________________________________________
// |       Object stats       | UAP v11 count | UAP v7 count |
// |__________________________|_______________|______________|
// | All CompositionObjects   |           175 |          125 |
// |--------------------------+---------------+--------------|
// | Expression animators     |            24 |           16 |
// | KeyFrame animators       |            20 |           12 |
// | Reference parameters     |            24 |           16 |
// | Expression operations    |            16 |           16 |
// |--------------------------+---------------+--------------|
// | Animated brushes         |             4 |            4 |
// | Animated gradient stops  |             - |            - |
// | ExpressionAnimations     |             7 |            5 |
// | PathKeyFrameAnimations   |             8 |            - |
// |--------------------------+---------------+--------------|
// | ContainerVisuals         |             3 |            3 |
// | ShapeVisuals             |             2 |            2 |
// |--------------------------+---------------+--------------|
// | ContainerShapes          |             7 |            7 |
// | CompositionSpriteShapes  |            14 |           14 |
// |--------------------------+---------------+--------------|
// | Brushes                  |             4 |            4 |
// | Gradient stops           |             - |            - |
// | CompositionVisualSurface |             - |            - |
// -----------------------------------------------------------
using Microsoft.Graphics.Canvas.Geometry;
using System;
using System.Collections.Generic;
using System.Numerics;
using Windows.Graphics;
using Windows.UI;
using Windows.UI.Composition;

namespace AnimatedVisuals
{
    // Name:        fire
    // Frame rate:  60 fps
    // Frame count: 120
    // Duration:    2000.0 mS
    // _____________________________________________________
    // | Marker | Constant | Frame |   mS   |   Progress   |
    // |________|__________|_______|________|______________|
    // | 1      | M_1      |     0 |    0.0 | 0F           |
    // | 2      | M_2      |    15 |  250.0 | 0.125416666F |
    // | 3      | M_3      |    30 |  500.0 | 0.250416666F |
    // | 4      | M_4      |    45 |  750.0 | 0.375416666F |
    // | 5      | M_5      |    60 | 1000.0 | 0.500416696F |
    // -----------------------------------------------------
    // ___________________________________________________________
    // | Theme property |   Accessor   | Type  |  Default value  |
    // |________________|______________|_______|_________________|
    // | #3197FE        | Color_3197FE | Color |    #FF3197FE    |
    // | #44311E        | Color_44311E | Color |    #FF44311E    |
    // | #6BCDFF        | Color_6BCDFF | Color |    #FF6BCDFF    |
    // | #FFFFFF        | Color_FFFFFF | Color | #FFFFFFFF White |
    // -----------------------------------------------------------
    sealed class Fire
        : Microsoft.UI.Xaml.Controls.IAnimatedVisualSource
    {
        // Animation duration: 2.000 seconds.
        internal const long c_durationTicks = 20000000;

        // Marker: 1.
        internal const float M_1 = 0F;

        // Marker: 2.
        internal const float M_2 = 0.125416666F;

        // Marker: 3.
        internal const float M_3 = 0.250416666F;

        // Marker: 4.
        internal const float M_4 = 0.375416666F;

        // Marker: 5.
        internal const float M_5 = 0.500416696F;

        // Theme property: Color_3197FE.
        internal static readonly Color c_themeColor_3197FE = Color.FromArgb(0xFF, 0x31, 0x97, 0xFE);

        // Theme property: Color_44311E.
        internal static readonly Color c_themeColor_44311E = Color.FromArgb(0xFF, 0x44, 0x31, 0x1E);

        // Theme property: Color_6BCDFF.
        internal static readonly Color c_themeColor_6BCDFF = Color.FromArgb(0xFF, 0x6B, 0xCD, 0xFF);

        // Theme property: Color_FFFFFF.
        internal static readonly Color c_themeColor_FFFFFF = Color.FromArgb(0xFF, 0xFF, 0xFF, 0xFF);

        CompositionPropertySet _themeProperties;
        Color _themeColor_3197FE = c_themeColor_3197FE;
        Color _themeColor_44311E = c_themeColor_44311E;
        Color _themeColor_6BCDFF = c_themeColor_6BCDFF;
        Color _themeColor_FFFFFF = c_themeColor_FFFFFF;

        // Theme properties.
        public Color Color_3197FE
        {
            get => _themeColor_3197FE;
            set
            {
                _themeColor_3197FE = value;
                if (_themeProperties != null)
                {
                    _themeProperties.InsertVector4("Color_3197FE", ColorAsVector4((Color)_themeColor_3197FE));
                }
            }
        }

        public Color Color_44311E
        {
            get => _themeColor_44311E;
            set
            {
                _themeColor_44311E = value;
                if (_themeProperties != null)
                {
                    _themeProperties.InsertVector4("Color_44311E", ColorAsVector4((Color)_themeColor_44311E));
                }
            }
        }

        public Color Color_6BCDFF
        {
            get => _themeColor_6BCDFF;
            set
            {
                _themeColor_6BCDFF = value;
                if (_themeProperties != null)
                {
                    _themeProperties.InsertVector4("Color_6BCDFF", ColorAsVector4((Color)_themeColor_6BCDFF));
                }
            }
        }

        public Color Color_FFFFFF
        {
            get => _themeColor_FFFFFF;
            set
            {
                _themeColor_FFFFFF = value;
                if (_themeProperties != null)
                {
                    _themeProperties.InsertVector4("Color_FFFFFF", ColorAsVector4((Color)_themeColor_FFFFFF));
                }
            }
        }

        static Vector4 ColorAsVector4(Color color) => new Vector4(color.R, color.G, color.B, color.A);

        CompositionPropertySet EnsureThemeProperties(Compositor compositor)
        {
            if (_themeProperties == null)
            {
                _themeProperties = compositor.CreatePropertySet();
                _themeProperties.InsertVector4("Color_3197FE", ColorAsVector4((Color)Color_3197FE));
                _themeProperties.InsertVector4("Color_44311E", ColorAsVector4((Color)Color_44311E));
                _themeProperties.InsertVector4("Color_6BCDFF", ColorAsVector4((Color)Color_6BCDFF));
                _themeProperties.InsertVector4("Color_FFFFFF", ColorAsVector4((Color)Color_FFFFFF));
            }
            return _themeProperties;
        }

        public Microsoft.UI.Xaml.Controls.IAnimatedVisual TryCreateAnimatedVisual(Compositor compositor)
        {
            object ignored = null;
            return TryCreateAnimatedVisual(compositor, out ignored);
        }

        public Microsoft.UI.Xaml.Controls.IAnimatedVisual TryCreateAnimatedVisual(Compositor compositor, out object diagnostics)
        {
            diagnostics = null;
            EnsureThemeProperties(compositor);

            if (Fire_AnimatedVisual_UAPv11.IsRuntimeCompatible())
            {
                return
                    new Fire_AnimatedVisual_UAPv11(
                        compositor,
                        _themeProperties
                        );
            }

            if (Fire_AnimatedVisual_UAPv7.IsRuntimeCompatible())
            {
                return
                    new Fire_AnimatedVisual_UAPv7(
                        compositor,
                        _themeProperties
                        );
            }

            return null;
        }

        /// <summary>
        /// Gets the number of frames in the animation.
        /// </summary>
        public double FrameCount => 120d;

        /// <summary>
        /// Gets the frame rate of the animation.
        /// </summary>
        public double Framerate => 60d;

        /// <summary>
        /// Gets the duration of the animation.
        /// </summary>
        public TimeSpan Duration => TimeSpan.FromTicks(c_durationTicks);

        /// <summary>
        /// Converts a zero-based frame number to the corresponding progress value denoting the
        /// start of the frame.
        /// </summary>
        public double FrameToProgress(double frameNumber)
        {
            return frameNumber / 120d;
        }

        /// <summary>
        /// Returns a map from marker names to corresponding progress values.
        /// </summary>
        public IReadOnlyDictionary<string, double> Markers =>
            new Dictionary<string, double>
            {
                { "1", 0d },
                { "2", 0.125416666666667 },
                { "3", 0.250416666666667 },
                { "4", 0.375416666666667 },
                { "5", 0.500416666666667 },
            };

        /// <summary>
        /// Sets the color property with the given name, or does nothing if no such property
        /// exists.
        /// </summary>
        public void SetColorProperty(string propertyName, Color value)
        {
            if (propertyName == "Color_3197FE")
            {
                _themeColor_3197FE = value;
            }
            else if (propertyName == "Color_44311E")
            {
                _themeColor_44311E = value;
            }
            else if (propertyName == "Color_6BCDFF")
            {
                _themeColor_6BCDFF = value;
            }
            else if (propertyName == "Color_FFFFFF")
            {
                _themeColor_FFFFFF = value;
            }
            else
            {
                return;
            }

            if (_themeProperties != null)
            {
                _themeProperties.InsertVector4(propertyName, ColorAsVector4(value));
            }
        }

        /// <summary>
        /// Sets the scalar property with the given name, or does nothing if no such property
        /// exists.
        /// </summary>
        public void SetScalarProperty(string propertyName, double value)
        {
        }

        sealed class Fire_AnimatedVisual_UAPv11 : Microsoft.UI.Xaml.Controls.IAnimatedVisual
        {
            const long c_durationTicks = 20000000;
            readonly Compositor _c;
            readonly ExpressionAnimation _reusableExpressionAnimation;
            readonly CompositionPropertySet _themeProperties;
            CompositionColorBrush _themeColor_Color_3197FE;
            CompositionColorBrush _themeColor_Color_44311E;
            CompositionColorBrush _themeColor_Color_6BCDFF;
            CompositionColorBrush _themeColor_Color_FFFFFF;
            CompositionPath _path_0;
            CompositionPath _path_1;
            CompositionPath _path_2;
            CompositionPath _path_3;
            CompositionPath _path_4;
            CompositionPath _path_5;
            CompositionPath _path_6;
            CompositionPath _path_7;
            CompositionPathGeometry _pathGeometry_1;
            CompositionPathGeometry _pathGeometry_9;
            ContainerVisual _root;
            CubicBezierEasingFunction _cubicBezierEasingFunction_0;
            CubicBezierEasingFunction _cubicBezierEasingFunction_1;
            ExpressionAnimation _rootProgress;
            StepEasingFunction _holdThenStepEasingFunction;
            StepEasingFunction _stepThenHoldEasingFunction;
            Vector2KeyFrameAnimation _scaleVector2Animation;
            Vector2KeyFrameAnimation _shapeVisibilityAnimation_0;
            Vector2KeyFrameAnimation _shapeVisibilityAnimation_1;
            Vector2KeyFrameAnimation _shapeVisibilityAnimation_2;
            Vector2KeyFrameAnimation _shapeVisibilityAnimation_3;

            static void StartProgressBoundAnimation(
                CompositionObject target,
                string animatedPropertyName,
                CompositionAnimation animation,
                ExpressionAnimation controllerProgressExpression)
            {
                target.StartAnimation(animatedPropertyName, animation);
                var controller = target.TryGetAnimationController(animatedPropertyName);
                controller.Pause();
                controller.StartAnimation("Progress", controllerProgressExpression);
            }

            void BindProperty(
                CompositionObject target,
                string animatedPropertyName,
                string expression,
                string referenceParameterName,
                CompositionObject referencedObject)
            {
                _reusableExpressionAnimation.ClearAllParameters();
                _reusableExpressionAnimation.Expression = expression;
                _reusableExpressionAnimation.SetReferenceParameter(referenceParameterName, referencedObject);
                target.StartAnimation(animatedPropertyName, _reusableExpressionAnimation);
            }

            PathKeyFrameAnimation CreatePathKeyFrameAnimation(float initialProgress, CompositionPath initialValue, CompositionEasingFunction initialEasingFunction)
            {
                var result = _c.CreatePathKeyFrameAnimation();
                result.Duration = TimeSpan.FromTicks(c_durationTicks);
                result.InsertKeyFrame(initialProgress, initialValue, initialEasingFunction);
                return result;
            }

            Vector2KeyFrameAnimation CreateVector2KeyFrameAnimation(float initialProgress, Vector2 initialValue, CompositionEasingFunction initialEasingFunction)
            {
                var result = _c.CreateVector2KeyFrameAnimation();
                result.Duration = TimeSpan.FromTicks(c_durationTicks);
                result.InsertKeyFrame(initialProgress, initialValue, initialEasingFunction);
                return result;
            }

            Vector3KeyFrameAnimation CreateVector3KeyFrameAnimation(float initialProgress, Vector3 initialValue, CompositionEasingFunction initialEasingFunction)
            {
                var result = _c.CreateVector3KeyFrameAnimation();
                result.Duration = TimeSpan.FromTicks(c_durationTicks);
                result.InsertKeyFrame(initialProgress, initialValue, initialEasingFunction);
                return result;
            }

            CompositionSpriteShape CreateSpriteShape(CompositionGeometry geometry, Matrix3x2 transformMatrix, CompositionBrush fillBrush)
            {
                var result = _c.CreateSpriteShape(geometry);
                result.TransformMatrix = transformMatrix;
                result.FillBrush = fillBrush;
                return result;
            }

            CanvasGeometry Geometry_0()
            {
                CanvasGeometry result;
                using (var builder = new CanvasPathBuilder(null))
                {
                    builder.SetFilledRegionDetermination(CanvasFilledRegionDetermination.Winding);
                    builder.BeginFigure(new Vector2(2F, 162.404007F));
                    builder.AddCubicBezier(new Vector2(-50F, 162.404007F), new Vector2(-152F, 122.305F), new Vector2(-152F, 26.4039993F));
                    builder.AddCubicBezier(new Vector2(-152F, -4.59600019F), new Vector2(-145F, -55.9039993F), new Vector2(-114F, -98.25F));
                    builder.AddCubicBezier(new Vector2(-83F, -140.595993F), new Vector2(-39F, -165.904007F), new Vector2(-9F, -158.25F));
                    builder.AddCubicBezier(new Vector2(21F, -150.595993F), new Vector2(-8.2840004F, -109.557999F), new Vector2(34F, -66.25F));
                    builder.AddCubicBezier(new Vector2(61F, -38.5970001F), new Vector2(100F, -15.5970001F), new Vector2(118F, 19.4029999F));
                    builder.AddCubicBezier(new Vector2(153F, 121.403F), new Vector2(54F, 162.404007F), new Vector2(2F, 162.404007F));
                    builder.EndFigure(CanvasFigureLoop.Closed);
                    result = CanvasGeometry.CreatePath(builder);
                }
                return result;
            }

            CanvasGeometry Geometry_1()
            {
                CanvasGeometry result;
                using (var builder = new CanvasPathBuilder(null))
                {
                    builder.SetFilledRegionDetermination(CanvasFilledRegionDetermination.Winding);
                    builder.BeginFigure(new Vector2(2F, 162.404007F));
                    builder.AddCubicBezier(new Vector2(-50F, 162.404007F), new Vector2(-144F, 130.403F), new Vector2(-126F, 23.4029999F));
                    builder.AddCubicBezier(new Vector2(-118F, -20.5970001F), new Vector2(-101F, -62.9039993F), new Vector2(-87F, -84.25F));
                    builder.AddCubicBezier(new Vector2(-73F, -105.596001F), new Vector2(-69F, -143.595993F), new Vector2(-45F, -158.557007F));
                    builder.AddCubicBezier(new Vector2(-19.9120007F, -174.195007F), new Vector2(20.9379997F, -138.335999F), new Vector2(63.2220001F, -95.0279999F));
                    builder.AddCubicBezier(new Vector2(90.2220001F, -67.375F), new Vector2(111F, -31.5960007F), new Vector2(123F, 15.4040003F));
                    builder.AddCubicBezier(new Vector2(149.539001F, 119.348999F), new Vector2(54F, 162.404007F), new Vector2(2F, 162.404007F));
                    builder.EndFigure(CanvasFigureLoop.Closed);
                    result = CanvasGeometry.CreatePath(builder);
                }
                return result;
            }

            CanvasGeometry Geometry_2()
            {
                CanvasGeometry result;
                using (var builder = new CanvasPathBuilder(null))
                {
                    builder.SetFilledRegionDetermination(CanvasFilledRegionDetermination.Winding);
                    builder.BeginFigure(new Vector2(2F, 162.404007F));
                    builder.AddCubicBezier(new Vector2(-50F, 162.404007F), new Vector2(-142F, 132.403F), new Vector2(-124F, 25.4029999F));
                    builder.AddCubicBezier(new Vector2(-116F, -18.5970001F), new Vector2(-74F, -55.9039993F), new Vector2(-48F, -82.25F));
                    builder.AddCubicBezier(new Vector2(-22F, -108.596001F), new Vector2(-5F, -161.824997F), new Vector2(13F, -162.171005F));
                    builder.AddCubicBezier(new Vector2(31F, -162.516998F), new Vector2(48.9379997F, -165.335999F), new Vector2(91.2220001F, -122.028F));
                    builder.AddCubicBezier(new Vector2(103F, -104.596001F), new Vector2(126F, -71.5970001F), new Vector2(136F, 16.4029999F));
                    builder.AddCubicBezier(new Vector2(148.888F, 129.813004F), new Vector2(54F, 162.404007F), new Vector2(2F, 162.404007F));
                    builder.EndFigure(CanvasFigureLoop.Closed);
                    result = CanvasGeometry.CreatePath(builder);
                }
                return result;
            }

            CanvasGeometry Geometry_3()
            {
                CanvasGeometry result;
                using (var builder = new CanvasPathBuilder(null))
                {
                    builder.SetFilledRegionDetermination(CanvasFilledRegionDetermination.Winding);
                    builder.BeginFigure(new Vector2(2F, 162.404007F));
                    builder.AddCubicBezier(new Vector2(-50F, 162.404007F), new Vector2(-156F, 124.403F), new Vector2(-138F, 17.4029999F));
                    builder.AddCubicBezier(new Vector2(-130F, -26.5970001F), new Vector2(-99F, -68.9039993F), new Vector2(-73F, -95.25F));
                    builder.AddCubicBezier(new Vector2(-47F, -121.596001F), new Vector2(31F, -165.201996F), new Vector2(57F, -158.399002F));
                    builder.AddCubicBezier(new Vector2(83F, -151.595993F), new Vector2(53.4440002F, -110.460999F), new Vector2(77.2220001F, -71.0289993F));
                    builder.AddCubicBezier(new Vector2(101F, -31.5970001F), new Vector2(114F, -8.59700012F), new Vector2(120F, 15.4029999F));
                    builder.AddCubicBezier(new Vector2(142F, 127.403F), new Vector2(54F, 162.404007F), new Vector2(2F, 162.404007F));
                    builder.EndFigure(CanvasFigureLoop.Closed);
                    result = CanvasGeometry.CreatePath(builder);
                }
                return result;
            }

            CanvasGeometry Geometry_4()
            {
                CanvasGeometry result;
                using (var builder = new CanvasPathBuilder(null))
                {
                    builder.BeginFigure(new Vector2(0F, 0F));
                    builder.EndFigure(CanvasFigureLoop.Closed);
                    result = CanvasGeometry.CreatePath(builder);
                }
                return result;
            }

            CanvasGeometry Geometry_5()
            {
                CanvasGeometry result;
                using (var builder = new CanvasPathBuilder(null))
                {
                    builder.SetFilledRegionDetermination(CanvasFilledRegionDetermination.Winding);
                    builder.BeginFigure(new Vector2(83F, 32.5F));
                    builder.AddCubicBezier(new Vector2(83F, -3.5F), new Vector2(67F, -7.33300018F), new Vector2(42F, -28.3330002F));
                    builder.AddCubicBezier(new Vector2(17F, -49.3330002F), new Vector2(17.9510002F, -66.25F), new Vector2(-1.33299994F, -66.25F));
                    builder.AddCubicBezier(new Vector2(-16.7910004F, -66.25F), new Vector2(-53.75F, -47.9169998F), new Vector2(-67.1959991F, -25.1429996F));
                    builder.AddCubicBezier(new Vector2(-81.9990005F, -0.0700000003F), new Vector2(-83F, 6.45200014F), new Vector2(-83F, 32.5F));
                    builder.AddCubicBezier(new Vector2(-83F, 71.1600037F), new Vector2(-45.8400002F, 92.5F), new Vector2(0F, 92.5F));
                    builder.AddCubicBezier(new Vector2(45.8400002F, 92.5F), new Vector2(83F, 71.1600037F), new Vector2(83F, 32.5F));
                    builder.EndFigure(CanvasFigureLoop.Closed);
                    result = CanvasGeometry.CreatePath(builder);
                }
                return result;
            }

            CanvasGeometry Geometry_6()
            {
                CanvasGeometry result;
                using (var builder = new CanvasPathBuilder(null))
                {
                    builder.SetFilledRegionDetermination(CanvasFilledRegionDetermination.Winding);
                    builder.BeginFigure(new Vector2(84.25F, 32.5F));
                    builder.AddCubicBezier(new Vector2(84.25F, -3.5F), new Vector2(65F, -18.75F), new Vector2(35.1669998F, -37.3330002F));
                    builder.AddCubicBezier(new Vector2(7.454F, -54.5950012F), new Vector2(-28.3320007F, -67.7060013F), new Vector2(-39.75F, -67.4169998F));
                    builder.AddCubicBezier(new Vector2(-52.9169998F, -67.0839996F), new Vector2(-59.8359985F, -57.4230003F), new Vector2(-69.0970001F, -29.9459991F));
                    builder.AddCubicBezier(new Vector2(-77.0839996F, -6.25F), new Vector2(-79F, 10.7399998F), new Vector2(-79F, 33F));
                    builder.AddCubicBezier(new Vector2(-79F, 71.6600037F), new Vector2(-45.8400002F, 92.5F), new Vector2(0F, 92.5F));
                    builder.AddCubicBezier(new Vector2(45.8400002F, 92.5F), new Vector2(84.25F, 71.1600037F), new Vector2(84.25F, 32.5F));
                    builder.EndFigure(CanvasFigureLoop.Closed);
                    result = CanvasGeometry.CreatePath(builder);
                }
                return result;
            }

            CanvasGeometry Geometry_7()
            {
                CanvasGeometry result;
                using (var builder = new CanvasPathBuilder(null))
                {
                    builder.SetFilledRegionDetermination(CanvasFilledRegionDetermination.Winding);
                    builder.BeginFigure(new Vector2(83.25F, 31F));
                    builder.AddCubicBezier(new Vector2(88.5F, -5.5F), new Vector2(86.6669998F, -16.25F), new Vector2(75F, -34.6669998F));
                    builder.AddCubicBezier(new Vector2(64.0910034F, -51.8880005F), new Vector2(28.2840004F, -67.8330002F), new Vector2(9F, -67.8330002F));
                    builder.AddCubicBezier(new Vector2(-9.00899982F, -67.8330002F), new Vector2(-13.8599997F, -52.3919983F), new Vector2(-27.1800003F, -34.9459991F));
                    builder.AddCubicBezier(new Vector2(-40.5F, -17.5F), new Vector2(-75.5F, -12.5F), new Vector2(-76.5F, 33F));
                    builder.AddCubicBezier(new Vector2(-77.348999F, 71.651001F), new Vector2(-45.8400002F, 92.5F), new Vector2(0F, 92.5F));
                    builder.AddCubicBezier(new Vector2(45.8400002F, 92.5F), new Vector2(77.7460022F, 69.2659988F), new Vector2(83.25F, 31F));
                    builder.EndFigure(CanvasFigureLoop.Closed);
                    result = CanvasGeometry.CreatePath(builder);
                }
                return result;
            }

            CanvasGeometry Geometry_8()
            {
                CanvasGeometry result;
                using (var builder = new CanvasPathBuilder(null))
                {
                    builder.SetFilledRegionDetermination(CanvasFilledRegionDetermination.Winding);
                    builder.BeginFigure(new Vector2(83.25F, 31.8330002F));
                    builder.AddCubicBezier(new Vector2(84.5830002F, 13.75F), new Vector2(84.4169998F, -3.08299994F), new Vector2(82.9169998F, -18.8330002F));
                    builder.AddCubicBezier(new Vector2(80.9840012F, -39.1259995F), new Vector2(66.6169968F, -67.75F), new Vector2(47.3330002F, -67.75F));
                    builder.AddCubicBezier(new Vector2(29.3239994F, -67.75F), new Vector2(9.5F, -51.6669998F), new Vector2(-12.1800003F, -36.612999F));
                    builder.AddCubicBezier(new Vector2(-30.2099991F, -24.0939999F), new Vector2(-78F, -12.5F), new Vector2(-79F, 33F));
                    builder.AddCubicBezier(new Vector2(-79.848999F, 71.651001F), new Vector2(-45.8400002F, 92.5F), new Vector2(0F, 92.5F));
                    builder.AddCubicBezier(new Vector2(45.8400002F, 92.5F), new Vector2(80.4069977F, 70.3880005F), new Vector2(83.25F, 31.8330002F));
                    builder.EndFigure(CanvasFigureLoop.Closed);
                    result = CanvasGeometry.CreatePath(builder);
                }
                return result;
            }

            CanvasGeometry Geometry_9()
            {
                CanvasGeometry result;
                using (var builder = new CanvasPathBuilder(null))
                {
                    builder.SetFilledRegionDetermination(CanvasFilledRegionDetermination.Winding);
                    builder.BeginFigure(new Vector2(0F, 17F));
                    builder.AddCubicBezier(new Vector2(-4.41800022F, 17F), new Vector2(-8F, 13.4180002F), new Vector2(-8F, 9F));
                    builder.AddLine(new Vector2(-8F, -9F));
                    builder.AddCubicBezier(new Vector2(-8F, -13.4180002F), new Vector2(-4.41800022F, -17F), new Vector2(0F, -17F));
                    builder.AddCubicBezier(new Vector2(4.41800022F, -17F), new Vector2(8F, -13.4180002F), new Vector2(8F, -9F));
                    builder.AddLine(new Vector2(8F, 9F));
                    builder.AddCubicBezier(new Vector2(8F, 13.4180002F), new Vector2(4.41800022F, 17F), new Vector2(0F, 17F));
                    builder.EndFigure(CanvasFigureLoop.Closed);
                    result = CanvasGeometry.CreatePath(builder);
                }
                return result;
            }

            // Color bound to theme property value: Color_3197FE
            CompositionColorBrush ThemeColor_Color_3197FE()
            {
                var result = _themeColor_Color_3197FE = _c.CreateColorBrush();
                BindProperty(result, "Color", "ColorRGB(_theme.Color_3197FE.W,_theme.Color_3197FE.X,_theme.Color_3197FE.Y,_theme.Color_3197FE.Z)", "_theme", _themeProperties);
                return result;
            }

            // Color bound to theme property value: Color_44311E
            CompositionColorBrush ThemeColor_Color_44311E()
            {
                var result = _themeColor_Color_44311E = _c.CreateColorBrush();
                BindProperty(result, "Color", "ColorRGB(_theme.Color_44311E.W,_theme.Color_44311E.X,_theme.Color_44311E.Y,_theme.Color_44311E.Z)", "_theme", _themeProperties);
                return result;
            }

            // Color bound to theme property value: Color_6BCDFF
            CompositionColorBrush ThemeColor_Color_6BCDFF()
            {
                var result = _themeColor_Color_6BCDFF = _c.CreateColorBrush();
                BindProperty(result, "Color", "ColorRGB(_theme.Color_6BCDFF.W,_theme.Color_6BCDFF.X,_theme.Color_6BCDFF.Y,_theme.Color_6BCDFF.Z)", "_theme", _themeProperties);
                return result;
            }

            // Color bound to theme property value: Color_FFFFFF
            CompositionColorBrush ThemeColor_Color_FFFFFF()
            {
                var result = _themeColor_Color_FFFFFF = _c.CreateColorBrush();
                BindProperty(result, "Color", "ColorRGB(_theme.Color_FFFFFF.W,_theme.Color_FFFFFF.X,_theme.Color_FFFFFF.Y,_theme.Color_FFFFFF.Z)", "_theme", _themeProperties);
                return result;
            }

            // - - PreComp layer: body
            // Layer aggregator
            // Layer: 外
            CompositionContainerShape ContainerShape_0()
            {
                var result = _c.CreateContainerShape();
                var shapes = result.Shapes;
                // Scale:1.5,1.5, Offset:<661.75, 420.94202>
                shapes.Add(SpriteShape_00());
                // Scale:1.5,1.5, Offset:<661.75, 420.94202>
                shapes.Add(SpriteShape_01());
                StartProgressBoundAnimation(result, "Scale", ShapeVisibilityAnimation_0(), _rootProgress);
                return result;
            }

            // - - PreComp layer: body
            // Layer aggregator
            // Layer: 外 2
            CompositionContainerShape ContainerShape_1()
            {
                var result = _c.CreateContainerShape();
                result.Scale = new Vector2(0F, 0F);
                var shapes = result.Shapes;
                // Scale:1.5,1.5, Offset:<661.75, 420.94202>
                shapes.Add(SpriteShape_02());
                // Scale:1.5,1.5, Offset:<661.75, 420.94202>
                shapes.Add(SpriteShape_03());
                StartProgressBoundAnimation(result, "Scale", ShapeVisibilityAnimation_1(), _rootProgress);
                return result;
            }

            // - - PreComp layer: body
            // Layer aggregator
            // Layer: 外 3
            CompositionContainerShape ContainerShape_2()
            {
                var result = _c.CreateContainerShape();
                result.Scale = new Vector2(0F, 0F);
                var shapes = result.Shapes;
                // Scale:1.5,1.5, Offset:<661.75, 420.94202>
                shapes.Add(SpriteShape_04());
                // Scale:1.5,1.5, Offset:<661.75, 420.94202>
                shapes.Add(SpriteShape_05());
                StartProgressBoundAnimation(result, "Scale", ShapeVisibilityAnimation_2(), _rootProgress);
                return result;
            }

            // - - PreComp layer: body
            // Layer aggregator
            // Layer: 外 4
            CompositionContainerShape ContainerShape_3()
            {
                var result = _c.CreateContainerShape();
                result.Scale = new Vector2(0F, 0F);
                var shapes = result.Shapes;
                // Scale:1.5,1.5, Offset:<661.75, 420.94202>
                shapes.Add(SpriteShape_06());
                // Scale:1.5,1.5, Offset:<661.75, 420.94202>
                shapes.Add(SpriteShape_07());
                StartProgressBoundAnimation(result, "Scale", ShapeVisibilityAnimation_3(), _rootProgress);
                return result;
            }

            // Layer aggregator
            CompositionContainerShape ContainerShape_4()
            {
                var result = _c.CreateContainerShape();
                result.CenterPoint = new Vector2(800F, 600F);
                result.Scale = new Vector2(1.5F, 1.5F);
                var shapes = result.Shapes;
                // Transforms: 右眼
                shapes.Add(ContainerShape_5());
                // Transforms: 左眼
                shapes.Add(ContainerShape_6());
                StartProgressBoundAnimation(result, "Offset", OffsetVector2Animation(), _rootProgress);
                return result;
            }

            // - Layer aggregator
            // Transforms for 右眼
            CompositionContainerShape ContainerShape_5()
            {
                var result = _c.CreateContainerShape();
                result.CenterPoint = new Vector2(8.25F, 17.25F);
                result.Offset = new Vector2(731.75F, 642.75F);
                // ShapeGroup: 组 1 Offset:<8.25, 17.25>
                result.Shapes.Add(SpriteShape_12());
                StartProgressBoundAnimation(result, "Scale", ScaleVector2Animation(), _rootProgress);
                return result;
            }

            // - Layer aggregator
            // Transforms for 左眼
            CompositionContainerShape ContainerShape_6()
            {
                var result = _c.CreateContainerShape();
                result.CenterPoint = new Vector2(8.25F, 17.25F);
                result.Offset = new Vector2(851.75F, 642.75F);
                // ShapeGroup: 组 1 Offset:<8.25, 17.25>
                result.Shapes.Add(SpriteShape_13());
                StartProgressBoundAnimation(result, "Scale", _scaleVector2Animation, _rootProgress);
                return result;
            }

            CompositionPath Path_0()
            {
                var result = _path_0 = new CompositionPath(Geometry_0());
                return result;
            }

            CompositionPath Path_1()
            {
                var result = _path_1 = new CompositionPath(Geometry_1());
                return result;
            }

            CompositionPath Path_2()
            {
                var result = _path_2 = new CompositionPath(Geometry_2());
                return result;
            }

            CompositionPath Path_3()
            {
                var result = _path_3 = new CompositionPath(Geometry_3());
                return result;
            }

            CompositionPath Path_4()
            {
                var result = _path_4 = new CompositionPath(Geometry_5());
                return result;
            }

            CompositionPath Path_5()
            {
                var result = _path_5 = new CompositionPath(Geometry_6());
                return result;
            }

            CompositionPath Path_6()
            {
                var result = _path_6 = new CompositionPath(Geometry_7());
                return result;
            }

            CompositionPath Path_7()
            {
                var result = _path_7 = new CompositionPath(Geometry_8());
                return result;
            }

            // - - - - PreComp layer: body
            // - - Layer aggregator
            // - Layer: 外
            // Scale:1.5,1.5, Offset:<661.75, 420.94202>
            CompositionPathGeometry PathGeometry_0()
            {
                var result = _c.CreatePathGeometry();
                StartProgressBoundAnimation(result, "Path", PathKeyFrameAnimation_0(), RootProgress());
                return result;
            }

            CompositionPathGeometry PathGeometry_1()
            {
                return _pathGeometry_1 = _c.CreatePathGeometry(new CompositionPath(Geometry_4()));
            }

            // - - - - PreComp layer: body
            // - - Layer aggregator
            // - Layer: 外 2
            // Scale:1.5,1.5, Offset:<661.75, 420.94202>
            CompositionPathGeometry PathGeometry_2()
            {
                var result = _c.CreatePathGeometry();
                StartProgressBoundAnimation(result, "Path", PathKeyFrameAnimation_1(), _rootProgress);
                return result;
            }

            // - - - - PreComp layer: body
            // - - Layer aggregator
            // - Layer: 外 3
            // Scale:1.5,1.5, Offset:<661.75, 420.94202>
            CompositionPathGeometry PathGeometry_3()
            {
                var result = _c.CreatePathGeometry();
                StartProgressBoundAnimation(result, "Path", PathKeyFrameAnimation_2(), _rootProgress);
                return result;
            }

            // - - - - PreComp layer: body
            // - - Layer aggregator
            // - Layer: 外 4
            // Scale:1.5,1.5, Offset:<661.75, 420.94202>
            CompositionPathGeometry PathGeometry_4()
            {
                var result = _c.CreatePathGeometry();
                StartProgressBoundAnimation(result, "Path", PathKeyFrameAnimation_3(), _rootProgress);
                return result;
            }

            // - - - PreComp layer: body
            // - Layer aggregator
            // Layer: 内 2
            CompositionPathGeometry PathGeometry_5()
            {
                var result = _c.CreatePathGeometry();
                result.StartAnimation("Path", PathKeyFrameAnimation_4());
                var controller = result.TryGetAnimationController("Path");
                controller.Pause();
                BindProperty(controller, "Progress", "_.Progress*0.9836066+0.01639344", "_", _root);
                return result;
            }

            // - - - PreComp layer: body
            // - Layer aggregator
            // Layer: 内 3
            CompositionPathGeometry PathGeometry_6()
            {
                var result = _c.CreatePathGeometry();
                StartProgressBoundAnimation(result, "Path", PathKeyFrameAnimation_5(), _rootProgress);
                return result;
            }

            // - - - PreComp layer: body
            // - Layer aggregator
            // Layer: 内 4
            CompositionPathGeometry PathGeometry_7()
            {
                var result = _c.CreatePathGeometry();
                StartProgressBoundAnimation(result, "Path", PathKeyFrameAnimation_6(), _rootProgress);
                return result;
            }

            // - - - PreComp layer: body
            // - Layer aggregator
            // Layer: 内 5
            CompositionPathGeometry PathGeometry_8()
            {
                var result = _c.CreatePathGeometry();
                result.StartAnimation("Path", PathKeyFrameAnimation_7());
                var controller = result.TryGetAnimationController("Path");
                controller.Pause();
                BindProperty(controller, "Progress", "_.Progress*0.9561753", "_", _root);
                return result;
            }

            CompositionPathGeometry PathGeometry_9()
            {
                return _pathGeometry_9 = _c.CreatePathGeometry(new CompositionPath(Geometry_9()));
            }

            // - - - PreComp layer: body
            // - Layer aggregator
            // Layer: 外
            // 路径 1
            CompositionSpriteShape SpriteShape_00()
            {
                // Offset:<798, 583.59607>, Scale:<1.5, 1.5>
                var geometry = PathGeometry_0();
                var result = CreateSpriteShape(geometry, new Matrix3x2(1.5F, 0F, 0F, 1.5F, 798F, 583.596069F), ThemeColor_Color_3197FE());
                return result;
            }

            // - - - PreComp layer: body
            // - Layer aggregator
            // Layer: 外
            // 路径 1
            CompositionSpriteShape SpriteShape_01()
            {
                // Offset:<593.625, 339.61502>, Scale:<1.5, 1.5>
                var geometry = PathGeometry_1();
                var result = CreateSpriteShape(geometry, new Matrix3x2(1.5F, 0F, 0F, 1.5F, 593.625F, 339.615021F), _themeColor_Color_3197FE);
                result.StrokeBrush = ThemeColor_Color_6BCDFF();
                result.StrokeMiterLimit = 2F;
                result.StrokeThickness = 4F;
                return result;
            }

            // - - - PreComp layer: body
            // - Layer aggregator
            // Layer: 外 2
            // 路径 1
            CompositionSpriteShape SpriteShape_02()
            {
                // Offset:<798, 583.59607>, Scale:<1.5, 1.5>
                var geometry = PathGeometry_2();
                var result = CreateSpriteShape(geometry, new Matrix3x2(1.5F, 0F, 0F, 1.5F, 798F, 583.596069F), _themeColor_Color_3197FE);
                return result;
            }

            // - - - PreComp layer: body
            // - Layer aggregator
            // Layer: 外 2
            // 路径 1
            CompositionSpriteShape SpriteShape_03()
            {
                // Offset:<593.625, 339.61502>, Scale:<1.5, 1.5>
                var geometry = _pathGeometry_1;
                var result = CreateSpriteShape(geometry, new Matrix3x2(1.5F, 0F, 0F, 1.5F, 593.625F, 339.615021F), _themeColor_Color_3197FE);
                result.StrokeBrush = _themeColor_Color_6BCDFF;
                result.StrokeMiterLimit = 2F;
                result.StrokeThickness = 4F;
                return result;
            }

            // - - - PreComp layer: body
            // - Layer aggregator
            // Layer: 外 3
            // 路径 1
            CompositionSpriteShape SpriteShape_04()
            {
                // Offset:<798, 583.59607>, Scale:<1.5, 1.5>
                var geometry = PathGeometry_3();
                var result = CreateSpriteShape(geometry, new Matrix3x2(1.5F, 0F, 0F, 1.5F, 798F, 583.596069F), _themeColor_Color_3197FE);
                return result;
            }

            // - - - PreComp layer: body
            // - Layer aggregator
            // Layer: 外 3
            // 路径 1
            CompositionSpriteShape SpriteShape_05()
            {
                // Offset:<593.625, 339.61502>, Scale:<1.5, 1.5>
                var geometry = _pathGeometry_1;
                var result = CreateSpriteShape(geometry, new Matrix3x2(1.5F, 0F, 0F, 1.5F, 593.625F, 339.615021F), _themeColor_Color_3197FE);
                result.StrokeBrush = _themeColor_Color_6BCDFF;
                result.StrokeMiterLimit = 2F;
                result.StrokeThickness = 4F;
                return result;
            }

            // - - - PreComp layer: body
            // - Layer aggregator
            // Layer: 外 4
            // 路径 1
            CompositionSpriteShape SpriteShape_06()
            {
                // Offset:<798, 583.59607>, Scale:<1.5, 1.5>
                var geometry = PathGeometry_4();
                var result = CreateSpriteShape(geometry, new Matrix3x2(1.5F, 0F, 0F, 1.5F, 798F, 583.596069F), _themeColor_Color_3197FE);
                return result;
            }

            // - - - PreComp layer: body
            // - Layer aggregator
            // Layer: 外 4
            // 路径 1
            CompositionSpriteShape SpriteShape_07()
            {
                // Offset:<593.625, 339.61502>, Scale:<1.5, 1.5>
                var geometry = _pathGeometry_1;
                var result = CreateSpriteShape(geometry, new Matrix3x2(1.5F, 0F, 0F, 1.5F, 593.625F, 339.615021F), _themeColor_Color_3197FE);
                result.StrokeBrush = _themeColor_Color_6BCDFF;
                result.StrokeMiterLimit = 2F;
                result.StrokeThickness = 4F;
                return result;
            }

            // - - PreComp layer: body
            // Layer aggregator
            // 路径 1
            CompositionSpriteShape SpriteShape_08()
            {
                // Offset:<800, 610.5>, Scale:<1.7, 1.7>
                var geometry = PathGeometry_5();
                var result = CreateSpriteShape(geometry, new Matrix3x2(1.70000005F, 0F, 0F, 1.70000005F, 800F, 610.5F), ThemeColor_Color_FFFFFF());
                StartProgressBoundAnimation(result, "Scale", _shapeVisibilityAnimation_0, _rootProgress);
                return result;
            }

            // - - PreComp layer: body
            // Layer aggregator
            // 路径 1
            CompositionSpriteShape SpriteShape_09()
            {
                // Offset:<800, 610.5>, Scale:<1.7, 1.7>
                var geometry = PathGeometry_6();
                var result = CreateSpriteShape(geometry, new Matrix3x2(1.70000005F, 0F, 0F, 1.70000005F, 800F, 610.5F), _themeColor_Color_FFFFFF);
                result.Scale = new Vector2(0F, 0F);
                StartProgressBoundAnimation(result, "Scale", _shapeVisibilityAnimation_1, _rootProgress);
                return result;
            }

            // - - PreComp layer: body
            // Layer aggregator
            // 路径 1
            CompositionSpriteShape SpriteShape_10()
            {
                // Offset:<800, 610.5>, Scale:<1.7, 1.7>
                var geometry = PathGeometry_7();
                var result = CreateSpriteShape(geometry, new Matrix3x2(1.70000005F, 0F, 0F, 1.70000005F, 800F, 610.5F), _themeColor_Color_FFFFFF);
                result.Scale = new Vector2(0F, 0F);
                StartProgressBoundAnimation(result, "Scale", _shapeVisibilityAnimation_2, _rootProgress);
                return result;
            }

            // - - PreComp layer: body
            // Layer aggregator
            // 路径 1
            CompositionSpriteShape SpriteShape_11()
            {
                // Offset:<800, 610.5>, Scale:<1.7, 1.7>
                var geometry = PathGeometry_8();
                var result = CreateSpriteShape(geometry, new Matrix3x2(1.70000005F, 0F, 0F, 1.70000005F, 800F, 610.5F), _themeColor_Color_FFFFFF);
                result.Scale = new Vector2(0F, 0F);
                StartProgressBoundAnimation(result, "Scale", _shapeVisibilityAnimation_3, _rootProgress);
                return result;
            }

            // - - Layer aggregator
            // Transforms: 右眼
            // 路径 1
            CompositionSpriteShape SpriteShape_12()
            {
                // Offset:<8.25, 17.25>
                var geometry = PathGeometry_9();
                var result = CreateSpriteShape(geometry, new Matrix3x2(1F, 0F, 0F, 1F, 8.25F, 17.25F), ThemeColor_Color_44311E());
                return result;
            }

            // - - Layer aggregator
            // Transforms: 左眼
            // 路径 1
            CompositionSpriteShape SpriteShape_13()
            {
                // Offset:<8.25, 17.25>
                var geometry = _pathGeometry_9;
                var result = CreateSpriteShape(geometry, new Matrix3x2(1F, 0F, 0F, 1F, 8.25F, 17.25F), _themeColor_Color_44311E);
                return result;
            }

            // Transforms for body
            ContainerVisual ContainerVisual_0()
            {
                var result = _c.CreateContainerVisual();
                result.CenterPoint = new Vector3(800F, 600F, 0F);
                result.Scale = new Vector3(1.5F, 1.5F, 0F);
                result.Children.InsertAtTop(ContainerVisual_1());
                StartProgressBoundAnimation(result, "Offset", OffsetVector3Animation(), _rootProgress);
                return result;
            }

            // PreComp layer: body
            ContainerVisual ContainerVisual_1()
            {
                var result = _c.CreateContainerVisual();
                result.Clip = InsetClip_0();
                result.Size = new Vector2(1600F, 1200F);
                // Layer aggregator
                result.Children.InsertAtTop(ShapeVisual_0());
                return result;
            }

            // The root of the composition.
            ContainerVisual Root()
            {
                var result = _root = _c.CreateContainerVisual();
                var propertySet = result.Properties;
                propertySet.InsertScalar("Progress", 0F);
                var children = result.Children;
                // PreComp layer: body
                children.InsertAtTop(ContainerVisual_0());
                // Layer aggregator
                children.InsertAtTop(ShapeVisual_1());
                return result;
            }

            CubicBezierEasingFunction CubicBezierEasingFunction_0()
            {
                return _cubicBezierEasingFunction_0 = _c.CreateCubicBezierEasingFunction(new Vector2(0.166999996F, 0.166999996F), new Vector2(0.833000004F, 0.833000004F));
            }

            CubicBezierEasingFunction CubicBezierEasingFunction_1()
            {
                return _cubicBezierEasingFunction_1 = _c.CreateCubicBezierEasingFunction(new Vector2(0.5F, 0F), new Vector2(0.5F, 1F));
            }

            ExpressionAnimation RootProgress()
            {
                var result = _rootProgress = _c.CreateExpressionAnimation("_.Progress");
                result.SetReferenceParameter("_", _root);
                return result;
            }

            // - PreComp layer: body
            InsetClip InsetClip_0()
            {
                var result = _c.CreateInsetClip();
                return result;
            }

            // - - - - - PreComp layer: body
            // - - - Layer aggregator
            // - - Layer: 外
            // -  Scale:1.5,1.5, Offset:<661.75, 420.94202>
            // Path
            PathKeyFrameAnimation PathKeyFrameAnimation_0()
            {
                // Frame 0.
                var result = CreatePathKeyFrameAnimation(0F, Path_0(), HoldThenStepEasingFunction());
                // Frame 7.5.
                result.InsertKeyFrame(0.0625F, Path_1(), CubicBezierEasingFunction_0());
                // Frame 15.
                result.InsertKeyFrame(0.125F, Path_2(), _cubicBezierEasingFunction_0);
                // Frame 22.5.
                result.InsertKeyFrame(0.1875F, Path_3(), _cubicBezierEasingFunction_0);
                // Frame 30.
                result.InsertKeyFrame(0.25F, _path_0, _cubicBezierEasingFunction_0);
                // Frame 37.5.
                result.InsertKeyFrame(0.3125F, _path_1, _cubicBezierEasingFunction_0);
                // Frame 45.
                result.InsertKeyFrame(0.375F, _path_2, _cubicBezierEasingFunction_0);
                // Frame 52.5.
                result.InsertKeyFrame(0.4375F, _path_3, _cubicBezierEasingFunction_0);
                // Frame 60.
                result.InsertKeyFrame(0.5F, _path_0, _cubicBezierEasingFunction_0);
                return result;
            }

            // - - - - - PreComp layer: body
            // - - - Layer aggregator
            // - - Layer: 外 2
            // -  Scale:1.5,1.5, Offset:<661.75, 420.94202>
            // Path
            PathKeyFrameAnimation PathKeyFrameAnimation_1()
            {
                // Frame 0.
                var result = CreatePathKeyFrameAnimation(0F, _path_0, StepThenHoldEasingFunction());
                // Frame 30.
                result.InsertKeyFrame(0.25F, _path_0, _holdThenStepEasingFunction);
                // Frame 37.5.
                result.InsertKeyFrame(0.3125F, _path_1, _cubicBezierEasingFunction_0);
                // Frame 45.
                result.InsertKeyFrame(0.375F, _path_2, _cubicBezierEasingFunction_0);
                // Frame 52.5.
                result.InsertKeyFrame(0.4375F, _path_3, _cubicBezierEasingFunction_0);
                // Frame 60.
                result.InsertKeyFrame(0.5F, _path_0, _cubicBezierEasingFunction_0);
                // Frame 67.5.
                result.InsertKeyFrame(0.5625F, _path_1, _cubicBezierEasingFunction_0);
                // Frame 75.
                result.InsertKeyFrame(0.625F, _path_2, _cubicBezierEasingFunction_0);
                // Frame 82.5.
                result.InsertKeyFrame(0.6875F, _path_3, _cubicBezierEasingFunction_0);
                // Frame 90.
                result.InsertKeyFrame(0.75F, _path_0, _cubicBezierEasingFunction_0);
                return result;
            }

            // - - - - - PreComp layer: body
            // - - - Layer aggregator
            // - - Layer: 外 3
            // -  Scale:1.5,1.5, Offset:<661.75, 420.94202>
            // Path
            PathKeyFrameAnimation PathKeyFrameAnimation_2()
            {
                // Frame 0.
                var result = CreatePathKeyFrameAnimation(0F, _path_0, _stepThenHoldEasingFunction);
                // Frame 60.
                result.InsertKeyFrame(0.5F, _path_0, _holdThenStepEasingFunction);
                // Frame 67.5.
                result.InsertKeyFrame(0.5625F, _path_1, _cubicBezierEasingFunction_0);
                // Frame 75.
                result.InsertKeyFrame(0.625F, _path_2, _cubicBezierEasingFunction_0);
                // Frame 82.5.
                result.InsertKeyFrame(0.6875F, _path_3, _cubicBezierEasingFunction_0);
                // Frame 90.
                result.InsertKeyFrame(0.75F, _path_0, _cubicBezierEasingFunction_0);
                // Frame 97.5.
                result.InsertKeyFrame(0.8125F, _path_1, _cubicBezierEasingFunction_0);
                // Frame 105.
                result.InsertKeyFrame(0.875F, _path_2, _cubicBezierEasingFunction_0);
                // Frame 112.5.
                result.InsertKeyFrame(0.9375F, _path_3, _cubicBezierEasingFunction_0);
                // Frame 120.
                result.InsertKeyFrame(1F, _path_0, _cubicBezierEasingFunction_0);
                return result;
            }

            // - - - - - PreComp layer: body
            // - - - Layer aggregator
            // - - Layer: 外 4
            // -  Scale:1.5,1.5, Offset:<661.75, 420.94202>
            // Path
            PathKeyFrameAnimation PathKeyFrameAnimation_3()
            {
                // Frame 0.
                var result = CreatePathKeyFrameAnimation(0F, _path_0, _stepThenHoldEasingFunction);
                // Frame 90.
                result.InsertKeyFrame(0.75F, _path_0, _holdThenStepEasingFunction);
                // Frame 97.5.
                result.InsertKeyFrame(0.8125F, _path_1, _cubicBezierEasingFunction_0);
                // Frame 105.
                result.InsertKeyFrame(0.875F, _path_2, _cubicBezierEasingFunction_0);
                // Frame 112.5.
                result.InsertKeyFrame(0.9375F, _path_3, _cubicBezierEasingFunction_0);
                // Frame 120.
                result.InsertKeyFrame(1F, _path_0, _cubicBezierEasingFunction_0);
                return result;
            }

            // - - - - PreComp layer: body
            // - - Layer aggregator
            // - Layer: 内 2
            // Path
            PathKeyFrameAnimation PathKeyFrameAnimation_4()
            {
                // Frame 0.
                var result = CreatePathKeyFrameAnimation(0F, Path_4(), _holdThenStepEasingFunction);
                // Frame 7.38.
                result.InsertKeyFrame(0.0614754111F, Path_5(), _cubicBezierEasingFunction_0);
                // Frame 14.75.
                result.InsertKeyFrame(0.122950822F, Path_6(), _cubicBezierEasingFunction_0);
                // Frame 22.13.
                result.InsertKeyFrame(0.184426233F, Path_7(), _cubicBezierEasingFunction_0);
                // Frame 29.51.
                result.InsertKeyFrame(0.245901644F, _path_4, _cubicBezierEasingFunction_0);
                // Frame 36.89.
                result.InsertKeyFrame(0.30737704F, _path_5, _cubicBezierEasingFunction_0);
                // Frame 44.26.
                result.InsertKeyFrame(0.368852466F, _path_6, _cubicBezierEasingFunction_0);
                // Frame 51.64.
                result.InsertKeyFrame(0.430327863F, _path_7, _cubicBezierEasingFunction_0);
                // Frame 59.02.
                result.InsertKeyFrame(0.491803288F, _path_4, _cubicBezierEasingFunction_0);
                return result;
            }

            // - - - - PreComp layer: body
            // - - Layer aggregator
            // - Layer: 内 3
            // Path
            PathKeyFrameAnimation PathKeyFrameAnimation_5()
            {
                // Frame 0.
                var result = CreatePathKeyFrameAnimation(0F, _path_4, _stepThenHoldEasingFunction);
                // Frame 28.
                result.InsertKeyFrame(0.233333334F, _path_4, _holdThenStepEasingFunction);
                // Frame 35.5.
                result.InsertKeyFrame(0.295833319F, _path_5, _cubicBezierEasingFunction_0);
                // Frame 43.
                result.InsertKeyFrame(0.358333319F, _path_6, _cubicBezierEasingFunction_0);
                // Frame 50.5.
                result.InsertKeyFrame(0.420833319F, _path_7, _cubicBezierEasingFunction_0);
                // Frame 58.
                result.InsertKeyFrame(0.483333319F, _path_4, _cubicBezierEasingFunction_0);
                // Frame 65.5.
                result.InsertKeyFrame(0.545833349F, _path_5, _cubicBezierEasingFunction_0);
                // Frame 73.
                result.InsertKeyFrame(0.608333349F, _path_6, _cubicBezierEasingFunction_0);
                // Frame 80.5.
                result.InsertKeyFrame(0.670833349F, _path_7, _cubicBezierEasingFunction_0);
                // Frame 88.
                result.InsertKeyFrame(0.733333349F, _path_4, _cubicBezierEasingFunction_0);
                return result;
            }

            // - - - - PreComp layer: body
            // - - Layer aggregator
            // - Layer: 内 4
            // Path
            PathKeyFrameAnimation PathKeyFrameAnimation_6()
            {
                // Frame 0.
                var result = CreatePathKeyFrameAnimation(0F, _path_4, _stepThenHoldEasingFunction);
                // Frame 58.
                result.InsertKeyFrame(0.483333319F, _path_4, _holdThenStepEasingFunction);
                // Frame 65.5.
                result.InsertKeyFrame(0.545833349F, _path_5, _cubicBezierEasingFunction_0);
                // Frame 73.
                result.InsertKeyFrame(0.608333349F, _path_6, _cubicBezierEasingFunction_0);
                // Frame 80.5.
                result.InsertKeyFrame(0.670833349F, _path_7, _cubicBezierEasingFunction_0);
                // Frame 88.
                result.InsertKeyFrame(0.733333349F, _path_4, _cubicBezierEasingFunction_0);
                // Frame 95.5.
                result.InsertKeyFrame(0.795833349F, _path_5, _cubicBezierEasingFunction_0);
                // Frame 103.
                result.InsertKeyFrame(0.858333349F, _path_6, _cubicBezierEasingFunction_0);
                // Frame 110.5.
                result.InsertKeyFrame(0.920833349F, _path_7, _cubicBezierEasingFunction_0);
                // Frame 118.
                result.InsertKeyFrame(0.983333349F, _path_4, _cubicBezierEasingFunction_0);
                return result;
            }

            // - - - - PreComp layer: body
            // - - Layer aggregator
            // - Layer: 内 5
            // Path
            PathKeyFrameAnimation PathKeyFrameAnimation_7()
            {
                // Frame 0.
                var result = CreatePathKeyFrameAnimation(0F, _path_4, _stepThenHoldEasingFunction);
                // Frame 84.14.
                result.InsertKeyFrame(0.70119524F, _path_4, _holdThenStepEasingFunction);
                // Frame 91.31.
                result.InsertKeyFrame(0.760956168F, _path_5, _cubicBezierEasingFunction_0);
                // Frame 98.49.
                result.InsertKeyFrame(0.820717156F, _path_6, _cubicBezierEasingFunction_0);
                // Frame 105.66.
                result.InsertKeyFrame(0.880478084F, _path_7, _cubicBezierEasingFunction_0);
                // Frame 112.83.
                result.InsertKeyFrame(0.940239072F, _path_4, _cubicBezierEasingFunction_0);
                // Frame 120.
                result.InsertKeyFrame(1F, _path_5, _cubicBezierEasingFunction_0);
                return result;
            }

            // - PreComp layer: body
            // Layer aggregator
            ShapeVisual ShapeVisual_0()
            {
                var result = _c.CreateShapeVisual();
                result.Size = new Vector2(1600F, 1200F);
                var shapes = result.Shapes;
                // Layer: 外
                shapes.Add(ContainerShape_0());
                // Layer: 外 2
                shapes.Add(ContainerShape_1());
                // Layer: 外 3
                shapes.Add(ContainerShape_2());
                // Layer: 外 4
                shapes.Add(ContainerShape_3());
                // Layer: 内 2
                shapes.Add(SpriteShape_08());
                // Layer: 内 3
                shapes.Add(SpriteShape_09());
                // Layer: 内 4
                shapes.Add(SpriteShape_10());
                // Layer: 内 5
                shapes.Add(SpriteShape_11());
                return result;
            }

            // Layer aggregator
            ShapeVisual ShapeVisual_1()
            {
                var result = _c.CreateShapeVisual();
                result.Size = new Vector2(1600F, 1200F);
                result.Shapes.Add(ContainerShape_4());
                return result;
            }

            StepEasingFunction HoldThenStepEasingFunction()
            {
                var result = _holdThenStepEasingFunction = _c.CreateStepEasingFunction();
                result.IsFinalStepSingleFrame = true;
                return result;
            }

            StepEasingFunction StepThenHoldEasingFunction()
            {
                var result = _stepThenHoldEasingFunction = _c.CreateStepEasingFunction();
                result.IsInitialStepSingleFrame = true;
                return result;
            }

            // - Layer aggregator
            // Offset
            Vector2KeyFrameAnimation OffsetVector2Animation()
            {
                // Frame 0.
                var result = CreateVector2KeyFrameAnimation(0F, new Vector2(0F, -55F), _holdThenStepEasingFunction);
                // Frame 60.
                result.InsertKeyFrame(0.5F, new Vector2(0F, 65F), _cubicBezierEasingFunction_1);
                // Frame 120.
                result.InsertKeyFrame(1F, new Vector2(0F, -55F), _cubicBezierEasingFunction_1);
                return result;
            }

            // Scale
            Vector2KeyFrameAnimation ScaleVector2Animation()
            {
                // Frame 0.
                var result = _scaleVector2Animation = CreateVector2KeyFrameAnimation(0F, new Vector2(1.5F, 1.5F), _holdThenStepEasingFunction);
                // Frame 10.
                result.InsertKeyFrame(0.0833333358F, new Vector2(1.5F, 0.300000012F), _cubicBezierEasingFunction_0);
                // Frame 20.
                result.InsertKeyFrame(0.166666672F, new Vector2(1.5F, 1.5F), _cubicBezierEasingFunction_0);
                // Frame 30.
                result.InsertKeyFrame(0.25F, new Vector2(1.5F, 0.300000012F), _cubicBezierEasingFunction_0);
                // Frame 40.
                result.InsertKeyFrame(0.333333343F, new Vector2(1.5F, 1.5F), _cubicBezierEasingFunction_0);
                return result;
            }

            Vector2KeyFrameAnimation ShapeVisibilityAnimation_0()
            {
                // Frame 30.
                var result = _shapeVisibilityAnimation_0 = CreateVector2KeyFrameAnimation(0.25F, new Vector2(0F, 0F), _holdThenStepEasingFunction);
                return result;
            }

            Vector2KeyFrameAnimation ShapeVisibilityAnimation_1()
            {
                // Frame 30.
                var result = _shapeVisibilityAnimation_1 = CreateVector2KeyFrameAnimation(0.25F, new Vector2(1F, 1F), _holdThenStepEasingFunction);
                // Frame 60.
                result.InsertKeyFrame(0.5F, new Vector2(0F, 0F), _holdThenStepEasingFunction);
                return result;
            }

            Vector2KeyFrameAnimation ShapeVisibilityAnimation_2()
            {
                // Frame 60.
                var result = _shapeVisibilityAnimation_2 = CreateVector2KeyFrameAnimation(0.5F, new Vector2(1F, 1F), _holdThenStepEasingFunction);
                // Frame 90.
                result.InsertKeyFrame(0.75F, new Vector2(0F, 0F), _holdThenStepEasingFunction);
                return result;
            }

            Vector2KeyFrameAnimation ShapeVisibilityAnimation_3()
            {
                // Frame 90.
                var result = _shapeVisibilityAnimation_3 = CreateVector2KeyFrameAnimation(0.75F, new Vector2(1F, 1F), _holdThenStepEasingFunction);
                return result;
            }

            // PreComp layer: body
            // Offset
            Vector3KeyFrameAnimation OffsetVector3Animation()
            {
                // Frame 0.
                var result = CreateVector3KeyFrameAnimation(0F, new Vector3(0F, -55F, 0F), _holdThenStepEasingFunction);
                // Frame 60.
                result.InsertKeyFrame(0.5F, new Vector3(0F, 65F, 0F), CubicBezierEasingFunction_1());
                // Frame 120.
                result.InsertKeyFrame(1F, new Vector3(0F, -55F, 0F), _cubicBezierEasingFunction_1);
                return result;
            }

            internal Fire_AnimatedVisual_UAPv11(
                Compositor compositor,
                CompositionPropertySet themeProperties
                )
            {
                _c = compositor;
                _themeProperties = themeProperties;
                _reusableExpressionAnimation = compositor.CreateExpressionAnimation();
                Root();
            }

            public Visual RootVisual => _root;
            public TimeSpan Duration => TimeSpan.FromTicks(c_durationTicks);
            public Vector2 Size => new Vector2(1600F, 1200F);
            void IDisposable.Dispose() => _root?.Dispose();

            internal static bool IsRuntimeCompatible()
            {
                return Windows.Foundation.Metadata.ApiInformation.IsApiContractPresent("Windows.Foundation.UniversalApiContract", 11);
            }
        }

        sealed class Fire_AnimatedVisual_UAPv7 : Microsoft.UI.Xaml.Controls.IAnimatedVisual
        {
            const long c_durationTicks = 20000000;
            readonly Compositor _c;
            readonly ExpressionAnimation _reusableExpressionAnimation;
            readonly CompositionPropertySet _themeProperties;
            CompositionColorBrush _themeColor_Color_3197FE;
            CompositionColorBrush _themeColor_Color_44311E;
            CompositionColorBrush _themeColor_Color_6BCDFF;
            CompositionColorBrush _themeColor_Color_FFFFFF;
            CompositionPathGeometry _pathGeometry_0;
            CompositionPathGeometry _pathGeometry_1;
            CompositionPathGeometry _pathGeometry_2;
            CompositionPathGeometry _pathGeometry_3;
            ContainerVisual _root;
            CubicBezierEasingFunction _cubicBezierEasingFunction_0;
            CubicBezierEasingFunction _cubicBezierEasingFunction_1;
            ExpressionAnimation _rootProgress;
            StepEasingFunction _holdThenStepEasingFunction;
            Vector2KeyFrameAnimation _scaleVector2Animation;
            Vector2KeyFrameAnimation _shapeVisibilityAnimation_0;
            Vector2KeyFrameAnimation _shapeVisibilityAnimation_1;
            Vector2KeyFrameAnimation _shapeVisibilityAnimation_2;
            Vector2KeyFrameAnimation _shapeVisibilityAnimation_3;

            static void StartProgressBoundAnimation(
                CompositionObject target,
                string animatedPropertyName,
                CompositionAnimation animation,
                ExpressionAnimation controllerProgressExpression)
            {
                target.StartAnimation(animatedPropertyName, animation);
                var controller = target.TryGetAnimationController(animatedPropertyName);
                controller.Pause();
                controller.StartAnimation("Progress", controllerProgressExpression);
            }

            void BindProperty(
                CompositionObject target,
                string animatedPropertyName,
                string expression,
                string referenceParameterName,
                CompositionObject referencedObject)
            {
                _reusableExpressionAnimation.ClearAllParameters();
                _reusableExpressionAnimation.Expression = expression;
                _reusableExpressionAnimation.SetReferenceParameter(referenceParameterName, referencedObject);
                target.StartAnimation(animatedPropertyName, _reusableExpressionAnimation);
            }

            Vector2KeyFrameAnimation CreateVector2KeyFrameAnimation(float initialProgress, Vector2 initialValue, CompositionEasingFunction initialEasingFunction)
            {
                var result = _c.CreateVector2KeyFrameAnimation();
                result.Duration = TimeSpan.FromTicks(c_durationTicks);
                result.InsertKeyFrame(initialProgress, initialValue, initialEasingFunction);
                return result;
            }

            Vector3KeyFrameAnimation CreateVector3KeyFrameAnimation(float initialProgress, Vector3 initialValue, CompositionEasingFunction initialEasingFunction)
            {
                var result = _c.CreateVector3KeyFrameAnimation();
                result.Duration = TimeSpan.FromTicks(c_durationTicks);
                result.InsertKeyFrame(initialProgress, initialValue, initialEasingFunction);
                return result;
            }

            CompositionSpriteShape CreateSpriteShape(CompositionGeometry geometry, Matrix3x2 transformMatrix, CompositionBrush fillBrush)
            {
                var result = _c.CreateSpriteShape(geometry);
                result.TransformMatrix = transformMatrix;
                result.FillBrush = fillBrush;
                return result;
            }

            CanvasGeometry Geometry_0()
            {
                CanvasGeometry result;
                using (var builder = new CanvasPathBuilder(null))
                {
                    builder.SetFilledRegionDetermination(CanvasFilledRegionDetermination.Winding);
                    builder.BeginFigure(new Vector2(2F, 162.404007F));
                    builder.AddCubicBezier(new Vector2(-50F, 162.404007F), new Vector2(-152F, 122.305F), new Vector2(-152F, 26.4039993F));
                    builder.AddCubicBezier(new Vector2(-152F, -4.59600019F), new Vector2(-145F, -55.9039993F), new Vector2(-114F, -98.25F));
                    builder.AddCubicBezier(new Vector2(-83F, -140.595993F), new Vector2(-39F, -165.904007F), new Vector2(-9F, -158.25F));
                    builder.AddCubicBezier(new Vector2(21F, -150.595993F), new Vector2(-8.2840004F, -109.557999F), new Vector2(34F, -66.25F));
                    builder.AddCubicBezier(new Vector2(61F, -38.5970001F), new Vector2(100F, -15.5970001F), new Vector2(118F, 19.4029999F));
                    builder.AddCubicBezier(new Vector2(153F, 121.403F), new Vector2(54F, 162.404007F), new Vector2(2F, 162.404007F));
                    builder.EndFigure(CanvasFigureLoop.Closed);
                    result = CanvasGeometry.CreatePath(builder);
                }
                return result;
            }

            CanvasGeometry Geometry_1()
            {
                CanvasGeometry result;
                using (var builder = new CanvasPathBuilder(null))
                {
                    builder.BeginFigure(new Vector2(0F, 0F));
                    builder.EndFigure(CanvasFigureLoop.Closed);
                    result = CanvasGeometry.CreatePath(builder);
                }
                return result;
            }

            CanvasGeometry Geometry_2()
            {
                CanvasGeometry result;
                using (var builder = new CanvasPathBuilder(null))
                {
                    builder.SetFilledRegionDetermination(CanvasFilledRegionDetermination.Winding);
                    builder.BeginFigure(new Vector2(83F, 32.5F));
                    builder.AddCubicBezier(new Vector2(83F, -3.5F), new Vector2(67F, -7.33300018F), new Vector2(42F, -28.3330002F));
                    builder.AddCubicBezier(new Vector2(17F, -49.3330002F), new Vector2(17.9510002F, -66.25F), new Vector2(-1.33299994F, -66.25F));
                    builder.AddCubicBezier(new Vector2(-16.7910004F, -66.25F), new Vector2(-53.75F, -47.9169998F), new Vector2(-67.1959991F, -25.1429996F));
                    builder.AddCubicBezier(new Vector2(-81.9990005F, -0.0700000003F), new Vector2(-83F, 6.45200014F), new Vector2(-83F, 32.5F));
                    builder.AddCubicBezier(new Vector2(-83F, 71.1600037F), new Vector2(-45.8400002F, 92.5F), new Vector2(0F, 92.5F));
                    builder.AddCubicBezier(new Vector2(45.8400002F, 92.5F), new Vector2(83F, 71.1600037F), new Vector2(83F, 32.5F));
                    builder.EndFigure(CanvasFigureLoop.Closed);
                    result = CanvasGeometry.CreatePath(builder);
                }
                return result;
            }

            CanvasGeometry Geometry_3()
            {
                CanvasGeometry result;
                using (var builder = new CanvasPathBuilder(null))
                {
                    builder.SetFilledRegionDetermination(CanvasFilledRegionDetermination.Winding);
                    builder.BeginFigure(new Vector2(0F, 17F));
                    builder.AddCubicBezier(new Vector2(-4.41800022F, 17F), new Vector2(-8F, 13.4180002F), new Vector2(-8F, 9F));
                    builder.AddLine(new Vector2(-8F, -9F));
                    builder.AddCubicBezier(new Vector2(-8F, -13.4180002F), new Vector2(-4.41800022F, -17F), new Vector2(0F, -17F));
                    builder.AddCubicBezier(new Vector2(4.41800022F, -17F), new Vector2(8F, -13.4180002F), new Vector2(8F, -9F));
                    builder.AddLine(new Vector2(8F, 9F));
                    builder.AddCubicBezier(new Vector2(8F, 13.4180002F), new Vector2(4.41800022F, 17F), new Vector2(0F, 17F));
                    builder.EndFigure(CanvasFigureLoop.Closed);
                    result = CanvasGeometry.CreatePath(builder);
                }
                return result;
            }

            // Color bound to theme property value: Color_3197FE
            CompositionColorBrush ThemeColor_Color_3197FE()
            {
                var result = _themeColor_Color_3197FE = _c.CreateColorBrush();
                BindProperty(result, "Color", "ColorRGB(_theme.Color_3197FE.W,_theme.Color_3197FE.X,_theme.Color_3197FE.Y,_theme.Color_3197FE.Z)", "_theme", _themeProperties);
                return result;
            }

            // Color bound to theme property value: Color_44311E
            CompositionColorBrush ThemeColor_Color_44311E()
            {
                var result = _themeColor_Color_44311E = _c.CreateColorBrush();
                BindProperty(result, "Color", "ColorRGB(_theme.Color_44311E.W,_theme.Color_44311E.X,_theme.Color_44311E.Y,_theme.Color_44311E.Z)", "_theme", _themeProperties);
                return result;
            }

            // Color bound to theme property value: Color_6BCDFF
            CompositionColorBrush ThemeColor_Color_6BCDFF()
            {
                var result = _themeColor_Color_6BCDFF = _c.CreateColorBrush();
                BindProperty(result, "Color", "ColorRGB(_theme.Color_6BCDFF.W,_theme.Color_6BCDFF.X,_theme.Color_6BCDFF.Y,_theme.Color_6BCDFF.Z)", "_theme", _themeProperties);
                return result;
            }

            // Color bound to theme property value: Color_FFFFFF
            CompositionColorBrush ThemeColor_Color_FFFFFF()
            {
                var result = _themeColor_Color_FFFFFF = _c.CreateColorBrush();
                BindProperty(result, "Color", "ColorRGB(_theme.Color_FFFFFF.W,_theme.Color_FFFFFF.X,_theme.Color_FFFFFF.Y,_theme.Color_FFFFFF.Z)", "_theme", _themeProperties);
                return result;
            }

            // - - PreComp layer: body
            // Layer aggregator
            // Layer: 外
            CompositionContainerShape ContainerShape_0()
            {
                var result = _c.CreateContainerShape();
                var shapes = result.Shapes;
                // Scale:1.5,1.5, Offset:<661.75, 420.94202>
                shapes.Add(SpriteShape_00());
                // Scale:1.5,1.5, Offset:<661.75, 420.94202>
                shapes.Add(SpriteShape_01());
                StartProgressBoundAnimation(result, "Scale", ShapeVisibilityAnimation_0(), RootProgress());
                return result;
            }

            // - - PreComp layer: body
            // Layer aggregator
            // Layer: 外 2
            CompositionContainerShape ContainerShape_1()
            {
                var result = _c.CreateContainerShape();
                result.Scale = new Vector2(0F, 0F);
                var shapes = result.Shapes;
                // Scale:1.5,1.5, Offset:<661.75, 420.94202>
                shapes.Add(SpriteShape_02());
                // Scale:1.5,1.5, Offset:<661.75, 420.94202>
                shapes.Add(SpriteShape_03());
                StartProgressBoundAnimation(result, "Scale", ShapeVisibilityAnimation_1(), _rootProgress);
                return result;
            }

            // - - PreComp layer: body
            // Layer aggregator
            // Layer: 外 3
            CompositionContainerShape ContainerShape_2()
            {
                var result = _c.CreateContainerShape();
                result.Scale = new Vector2(0F, 0F);
                var shapes = result.Shapes;
                // Scale:1.5,1.5, Offset:<661.75, 420.94202>
                shapes.Add(SpriteShape_04());
                // Scale:1.5,1.5, Offset:<661.75, 420.94202>
                shapes.Add(SpriteShape_05());
                StartProgressBoundAnimation(result, "Scale", ShapeVisibilityAnimation_2(), _rootProgress);
                return result;
            }

            // - - PreComp layer: body
            // Layer aggregator
            // Layer: 外 4
            CompositionContainerShape ContainerShape_3()
            {
                var result = _c.CreateContainerShape();
                result.Scale = new Vector2(0F, 0F);
                var shapes = result.Shapes;
                // Scale:1.5,1.5, Offset:<661.75, 420.94202>
                shapes.Add(SpriteShape_06());
                // Scale:1.5,1.5, Offset:<661.75, 420.94202>
                shapes.Add(SpriteShape_07());
                StartProgressBoundAnimation(result, "Scale", ShapeVisibilityAnimation_3(), _rootProgress);
                return result;
            }

            // Layer aggregator
            CompositionContainerShape ContainerShape_4()
            {
                var result = _c.CreateContainerShape();
                result.CenterPoint = new Vector2(800F, 600F);
                result.Scale = new Vector2(1.5F, 1.5F);
                var shapes = result.Shapes;
                // Transforms: 右眼
                shapes.Add(ContainerShape_5());
                // Transforms: 左眼
                shapes.Add(ContainerShape_6());
                StartProgressBoundAnimation(result, "Offset", OffsetVector2Animation(), _rootProgress);
                return result;
            }

            // - Layer aggregator
            // Transforms for 右眼
            CompositionContainerShape ContainerShape_5()
            {
                var result = _c.CreateContainerShape();
                result.CenterPoint = new Vector2(8.25F, 17.25F);
                result.Offset = new Vector2(731.75F, 642.75F);
                // ShapeGroup: 组 1 Offset:<8.25, 17.25>
                result.Shapes.Add(SpriteShape_12());
                StartProgressBoundAnimation(result, "Scale", ScaleVector2Animation(), _rootProgress);
                return result;
            }

            // - Layer aggregator
            // Transforms for 左眼
            CompositionContainerShape ContainerShape_6()
            {
                var result = _c.CreateContainerShape();
                result.CenterPoint = new Vector2(8.25F, 17.25F);
                result.Offset = new Vector2(851.75F, 642.75F);
                // ShapeGroup: 组 1 Offset:<8.25, 17.25>
                result.Shapes.Add(SpriteShape_13());
                StartProgressBoundAnimation(result, "Scale", _scaleVector2Animation, _rootProgress);
                return result;
            }

            CompositionPathGeometry PathGeometry_0()
            {
                return _pathGeometry_0 = _c.CreatePathGeometry(new CompositionPath(Geometry_0()));
            }

            CompositionPathGeometry PathGeometry_1()
            {
                return _pathGeometry_1 = _c.CreatePathGeometry(new CompositionPath(Geometry_1()));
            }

            CompositionPathGeometry PathGeometry_2()
            {
                return _pathGeometry_2 = _c.CreatePathGeometry(new CompositionPath(Geometry_2()));
            }

            CompositionPathGeometry PathGeometry_3()
            {
                return _pathGeometry_3 = _c.CreatePathGeometry(new CompositionPath(Geometry_3()));
            }

            // - - - PreComp layer: body
            // - Layer aggregator
            // Layer: 外
            // 路径 1
            CompositionSpriteShape SpriteShape_00()
            {
                // Offset:<798, 583.59607>, Scale:<1.5, 1.5>
                var geometry = PathGeometry_0();
                var result = CreateSpriteShape(geometry, new Matrix3x2(1.5F, 0F, 0F, 1.5F, 798F, 583.596069F), ThemeColor_Color_3197FE());
                return result;
            }

            // - - - PreComp layer: body
            // - Layer aggregator
            // Layer: 外
            // 路径 1
            CompositionSpriteShape SpriteShape_01()
            {
                // Offset:<593.625, 339.61502>, Scale:<1.5, 1.5>
                var geometry = PathGeometry_1();
                var result = CreateSpriteShape(geometry, new Matrix3x2(1.5F, 0F, 0F, 1.5F, 593.625F, 339.615021F), _themeColor_Color_3197FE);
                result.StrokeBrush = ThemeColor_Color_6BCDFF();
                result.StrokeMiterLimit = 2F;
                result.StrokeThickness = 4F;
                return result;
            }

            // - - - PreComp layer: body
            // - Layer aggregator
            // Layer: 外 2
            // 路径 1
            CompositionSpriteShape SpriteShape_02()
            {
                // Offset:<798, 583.59607>, Scale:<1.5, 1.5>
                var geometry = _pathGeometry_0;
                var result = CreateSpriteShape(geometry, new Matrix3x2(1.5F, 0F, 0F, 1.5F, 798F, 583.596069F), _themeColor_Color_3197FE);
                return result;
            }

            // - - - PreComp layer: body
            // - Layer aggregator
            // Layer: 外 2
            // 路径 1
            CompositionSpriteShape SpriteShape_03()
            {
                // Offset:<593.625, 339.61502>, Scale:<1.5, 1.5>
                var geometry = _pathGeometry_1;
                var result = CreateSpriteShape(geometry, new Matrix3x2(1.5F, 0F, 0F, 1.5F, 593.625F, 339.615021F), _themeColor_Color_3197FE);
                result.StrokeBrush = _themeColor_Color_6BCDFF;
                result.StrokeMiterLimit = 2F;
                result.StrokeThickness = 4F;
                return result;
            }

            // - - - PreComp layer: body
            // - Layer aggregator
            // Layer: 外 3
            // 路径 1
            CompositionSpriteShape SpriteShape_04()
            {
                // Offset:<798, 583.59607>, Scale:<1.5, 1.5>
                var geometry = _pathGeometry_0;
                var result = CreateSpriteShape(geometry, new Matrix3x2(1.5F, 0F, 0F, 1.5F, 798F, 583.596069F), _themeColor_Color_3197FE);
                return result;
            }

            // - - - PreComp layer: body
            // - Layer aggregator
            // Layer: 外 3
            // 路径 1
            CompositionSpriteShape SpriteShape_05()
            {
                // Offset:<593.625, 339.61502>, Scale:<1.5, 1.5>
                var geometry = _pathGeometry_1;
                var result = CreateSpriteShape(geometry, new Matrix3x2(1.5F, 0F, 0F, 1.5F, 593.625F, 339.615021F), _themeColor_Color_3197FE);
                result.StrokeBrush = _themeColor_Color_6BCDFF;
                result.StrokeMiterLimit = 2F;
                result.StrokeThickness = 4F;
                return result;
            }

            // - - - PreComp layer: body
            // - Layer aggregator
            // Layer: 外 4
            // 路径 1
            CompositionSpriteShape SpriteShape_06()
            {
                // Offset:<798, 583.59607>, Scale:<1.5, 1.5>
                var geometry = _pathGeometry_0;
                var result = CreateSpriteShape(geometry, new Matrix3x2(1.5F, 0F, 0F, 1.5F, 798F, 583.596069F), _themeColor_Color_3197FE);
                return result;
            }

            // - - - PreComp layer: body
            // - Layer aggregator
            // Layer: 外 4
            // 路径 1
            CompositionSpriteShape SpriteShape_07()
            {
                // Offset:<593.625, 339.61502>, Scale:<1.5, 1.5>
                var geometry = _pathGeometry_1;
                var result = CreateSpriteShape(geometry, new Matrix3x2(1.5F, 0F, 0F, 1.5F, 593.625F, 339.615021F), _themeColor_Color_3197FE);
                result.StrokeBrush = _themeColor_Color_6BCDFF;
                result.StrokeMiterLimit = 2F;
                result.StrokeThickness = 4F;
                return result;
            }

            // - - PreComp layer: body
            // Layer aggregator
            // 路径 1
            CompositionSpriteShape SpriteShape_08()
            {
                // Offset:<800, 610.5>, Scale:<1.7, 1.7>
                var geometry = PathGeometry_2();
                var result = CreateSpriteShape(geometry, new Matrix3x2(1.70000005F, 0F, 0F, 1.70000005F, 800F, 610.5F), ThemeColor_Color_FFFFFF());
                StartProgressBoundAnimation(result, "Scale", _shapeVisibilityAnimation_0, _rootProgress);
                return result;
            }

            // - - PreComp layer: body
            // Layer aggregator
            // 路径 1
            CompositionSpriteShape SpriteShape_09()
            {
                // Offset:<800, 610.5>, Scale:<1.7, 1.7>
                var geometry = _pathGeometry_2;
                var result = CreateSpriteShape(geometry, new Matrix3x2(1.70000005F, 0F, 0F, 1.70000005F, 800F, 610.5F), _themeColor_Color_FFFFFF);
                result.Scale = new Vector2(0F, 0F);
                StartProgressBoundAnimation(result, "Scale", _shapeVisibilityAnimation_1, _rootProgress);
                return result;
            }

            // - - PreComp layer: body
            // Layer aggregator
            // 路径 1
            CompositionSpriteShape SpriteShape_10()
            {
                // Offset:<800, 610.5>, Scale:<1.7, 1.7>
                var geometry = _pathGeometry_2;
                var result = CreateSpriteShape(geometry, new Matrix3x2(1.70000005F, 0F, 0F, 1.70000005F, 800F, 610.5F), _themeColor_Color_FFFFFF);
                result.Scale = new Vector2(0F, 0F);
                StartProgressBoundAnimation(result, "Scale", _shapeVisibilityAnimation_2, _rootProgress);
                return result;
            }

            // - - PreComp layer: body
            // Layer aggregator
            // 路径 1
            CompositionSpriteShape SpriteShape_11()
            {
                // Offset:<800, 610.5>, Scale:<1.7, 1.7>
                var geometry = _pathGeometry_2;
                var result = CreateSpriteShape(geometry, new Matrix3x2(1.70000005F, 0F, 0F, 1.70000005F, 800F, 610.5F), _themeColor_Color_FFFFFF);
                result.Scale = new Vector2(0F, 0F);
                StartProgressBoundAnimation(result, "Scale", _shapeVisibilityAnimation_3, _rootProgress);
                return result;
            }

            // - - Layer aggregator
            // Transforms: 右眼
            // 路径 1
            CompositionSpriteShape SpriteShape_12()
            {
                // Offset:<8.25, 17.25>
                var geometry = PathGeometry_3();
                var result = CreateSpriteShape(geometry, new Matrix3x2(1F, 0F, 0F, 1F, 8.25F, 17.25F), ThemeColor_Color_44311E());
                return result;
            }

            // - - Layer aggregator
            // Transforms: 左眼
            // 路径 1
            CompositionSpriteShape SpriteShape_13()
            {
                // Offset:<8.25, 17.25>
                var geometry = _pathGeometry_3;
                var result = CreateSpriteShape(geometry, new Matrix3x2(1F, 0F, 0F, 1F, 8.25F, 17.25F), _themeColor_Color_44311E);
                return result;
            }

            // Transforms for body
            ContainerVisual ContainerVisual_0()
            {
                var result = _c.CreateContainerVisual();
                result.CenterPoint = new Vector3(800F, 600F, 0F);
                result.Scale = new Vector3(1.5F, 1.5F, 0F);
                result.Children.InsertAtTop(ContainerVisual_1());
                StartProgressBoundAnimation(result, "Offset", OffsetVector3Animation(), _rootProgress);
                return result;
            }

            // PreComp layer: body
            ContainerVisual ContainerVisual_1()
            {
                var result = _c.CreateContainerVisual();
                result.Clip = InsetClip_0();
                result.Size = new Vector2(1600F, 1200F);
                // Layer aggregator
                result.Children.InsertAtTop(ShapeVisual_0());
                return result;
            }

            // The root of the composition.
            ContainerVisual Root()
            {
                var result = _root = _c.CreateContainerVisual();
                var propertySet = result.Properties;
                propertySet.InsertScalar("Progress", 0F);
                var children = result.Children;
                // PreComp layer: body
                children.InsertAtTop(ContainerVisual_0());
                // Layer aggregator
                children.InsertAtTop(ShapeVisual_1());
                return result;
            }

            CubicBezierEasingFunction CubicBezierEasingFunction_0()
            {
                return _cubicBezierEasingFunction_0 = _c.CreateCubicBezierEasingFunction(new Vector2(0.5F, 0F), new Vector2(0.5F, 1F));
            }

            CubicBezierEasingFunction CubicBezierEasingFunction_1()
            {
                return _cubicBezierEasingFunction_1 = _c.CreateCubicBezierEasingFunction(new Vector2(0.166999996F, 0.166999996F), new Vector2(0.833000004F, 0.833000004F));
            }

            ExpressionAnimation RootProgress()
            {
                var result = _rootProgress = _c.CreateExpressionAnimation("_.Progress");
                result.SetReferenceParameter("_", _root);
                return result;
            }

            // - PreComp layer: body
            InsetClip InsetClip_0()
            {
                var result = _c.CreateInsetClip();
                return result;
            }

            // - PreComp layer: body
            // Layer aggregator
            ShapeVisual ShapeVisual_0()
            {
                var result = _c.CreateShapeVisual();
                result.Size = new Vector2(1600F, 1200F);
                var shapes = result.Shapes;
                // Layer: 外
                shapes.Add(ContainerShape_0());
                // Layer: 外 2
                shapes.Add(ContainerShape_1());
                // Layer: 外 3
                shapes.Add(ContainerShape_2());
                // Layer: 外 4
                shapes.Add(ContainerShape_3());
                // Layer: 内 2
                shapes.Add(SpriteShape_08());
                // Layer: 内 3
                shapes.Add(SpriteShape_09());
                // Layer: 内 4
                shapes.Add(SpriteShape_10());
                // Layer: 内 5
                shapes.Add(SpriteShape_11());
                return result;
            }

            // Layer aggregator
            ShapeVisual ShapeVisual_1()
            {
                var result = _c.CreateShapeVisual();
                result.Size = new Vector2(1600F, 1200F);
                result.Shapes.Add(ContainerShape_4());
                return result;
            }

            StepEasingFunction HoldThenStepEasingFunction()
            {
                var result = _holdThenStepEasingFunction = _c.CreateStepEasingFunction();
                result.IsFinalStepSingleFrame = true;
                return result;
            }

            // - Layer aggregator
            // Offset
            Vector2KeyFrameAnimation OffsetVector2Animation()
            {
                // Frame 0.
                var result = CreateVector2KeyFrameAnimation(0F, new Vector2(0F, -55F), _holdThenStepEasingFunction);
                // Frame 60.
                result.InsertKeyFrame(0.5F, new Vector2(0F, 65F), _cubicBezierEasingFunction_0);
                // Frame 120.
                result.InsertKeyFrame(1F, new Vector2(0F, -55F), _cubicBezierEasingFunction_0);
                return result;
            }

            // Scale
            Vector2KeyFrameAnimation ScaleVector2Animation()
            {
                // Frame 0.
                var result = _scaleVector2Animation = CreateVector2KeyFrameAnimation(0F, new Vector2(1.5F, 1.5F), _holdThenStepEasingFunction);
                // Frame 10.
                result.InsertKeyFrame(0.0833333358F, new Vector2(1.5F, 0.300000012F), CubicBezierEasingFunction_1());
                // Frame 20.
                result.InsertKeyFrame(0.166666672F, new Vector2(1.5F, 1.5F), _cubicBezierEasingFunction_1);
                // Frame 30.
                result.InsertKeyFrame(0.25F, new Vector2(1.5F, 0.300000012F), _cubicBezierEasingFunction_1);
                // Frame 40.
                result.InsertKeyFrame(0.333333343F, new Vector2(1.5F, 1.5F), _cubicBezierEasingFunction_1);
                return result;
            }

            Vector2KeyFrameAnimation ShapeVisibilityAnimation_0()
            {
                // Frame 30.
                var result = _shapeVisibilityAnimation_0 = CreateVector2KeyFrameAnimation(0.25F, new Vector2(0F, 0F), HoldThenStepEasingFunction());
                return result;
            }

            Vector2KeyFrameAnimation ShapeVisibilityAnimation_1()
            {
                // Frame 30.
                var result = _shapeVisibilityAnimation_1 = CreateVector2KeyFrameAnimation(0.25F, new Vector2(1F, 1F), _holdThenStepEasingFunction);
                // Frame 60.
                result.InsertKeyFrame(0.5F, new Vector2(0F, 0F), _holdThenStepEasingFunction);
                return result;
            }

            Vector2KeyFrameAnimation ShapeVisibilityAnimation_2()
            {
                // Frame 60.
                var result = _shapeVisibilityAnimation_2 = CreateVector2KeyFrameAnimation(0.5F, new Vector2(1F, 1F), _holdThenStepEasingFunction);
                // Frame 90.
                result.InsertKeyFrame(0.75F, new Vector2(0F, 0F), _holdThenStepEasingFunction);
                return result;
            }

            Vector2KeyFrameAnimation ShapeVisibilityAnimation_3()
            {
                // Frame 90.
                var result = _shapeVisibilityAnimation_3 = CreateVector2KeyFrameAnimation(0.75F, new Vector2(1F, 1F), _holdThenStepEasingFunction);
                return result;
            }

            // PreComp layer: body
            // Offset
            Vector3KeyFrameAnimation OffsetVector3Animation()
            {
                // Frame 0.
                var result = CreateVector3KeyFrameAnimation(0F, new Vector3(0F, -55F, 0F), _holdThenStepEasingFunction);
                // Frame 60.
                result.InsertKeyFrame(0.5F, new Vector3(0F, 65F, 0F), CubicBezierEasingFunction_0());
                // Frame 120.
                result.InsertKeyFrame(1F, new Vector3(0F, -55F, 0F), _cubicBezierEasingFunction_0);
                return result;
            }

            internal Fire_AnimatedVisual_UAPv7(
                Compositor compositor,
                CompositionPropertySet themeProperties
                )
            {
                _c = compositor;
                _themeProperties = themeProperties;
                _reusableExpressionAnimation = compositor.CreateExpressionAnimation();
                Root();
            }

            public Visual RootVisual => _root;
            public TimeSpan Duration => TimeSpan.FromTicks(c_durationTicks);
            public Vector2 Size => new Vector2(1600F, 1200F);
            void IDisposable.Dispose() => _root?.Dispose();

            internal static bool IsRuntimeCompatible()
            {
                return Windows.Foundation.Metadata.ApiInformation.IsApiContractPresent("Windows.Foundation.UniversalApiContract", 7);
            }
        }
    }
}
